<?php
/**
 * Created by PhpStorm.
 * User: huang
 * Date: 2017/10/14
 * Time: 12:27
 */

namespace app\models\table;


use common\core\BaseActiveRecord;

class ArticleInfo extends BaseActiveRecord
{

    const STATUS_IS_AUDIT=2;//审核通过

    public static function tableName()
    {
        return '{{%article_info}}'; // TODO: Change the autogenerated stub
    }

}