<?php
/**
 * Created by PhpStorm.
 * User: huang
 * Date: 2017/10/6
 * Time: 23:06
 */

namespace app\models\table;


use common\core\BaseActiveRecord;

class BridgeLoanMonthTable extends BaseActiveRecord
{

    public static function tableName()
    {
        return '{{%bridge_loan_month_table}}'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}