<?php
/**
 * Created by PhpStorm.
 * User: huang
 * Date: 2017/10/7
 * Time: 17:46
 */

namespace api\controllers;


use app\component\controller\BaseController;
use app\component\filter\ApiSessionFilter;
use app\component\model\Page;
use app\component\session\SessionContainer;
use app\services\ArticleService;
use common\error\Error;
use yii\helpers\VarDumper;

/**
 * Class ForumController
 * @package api\controllers
 * @controller-name 论坛模块
 */
class ForumController extends BaseController
{

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'session' => [
                'class' => ApiSessionFilter::className(),
                'only' => ['article-publish', 'comment']
            ]
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * @api-name 文章列表
     * @api-method GET
     * @api-url forum/article-list
     * @api-param int $cate 类别（可选 1-银行之家 2-物业 默认所有）
     * @api-param int $type 类型（new-最新文章 hot-精选文章 选填）
     * @api-param int $page 页码
     * @api-param int $pageSize 每页数量
     * @api-response {
     *  "data": {
     *     "page": {
     *        "current": 1,当前页
     *        "total": 1,总页数
     *        "count": 1,总条数
     *        "size": 20,每页展示条数
     *      },
     *  "items": [
     *        {
     *     "id": 1,文章id
     *     "cate": 1,类别
     *     "cateTitle":"银行之家"，类别标题
     *     "logo": null,文章logo
     *     "title": "测试呢文章1",文章标题
     *     "author": "xxx",作者
     *     "createTime": "2017-10-14 12:31:28"，发布时间
     *        }
     *     ...
     *      ]
     *    }
     * }
     */
    public function actionArticleList()
    {
        $cate = \Yii::$app->request->get('cate');
        $type = \Yii::$app->request->get('type');
        $page = \Yii::$app->request->get('page');
        $pageSize = \Yii::$app->request->get('pageSize');
        $pager = new Page($page, $pageSize);
        $result = ArticleService::instance()->getArticleList($cate, $type, $pager);
        if (is_null($result))
            \Yii::$app->response->error();
        \Yii::$app->response->success($result);
    }

    /**
     * @api-name 文章发布
     * @api-method POST
     * @api-url forum/article-publish
     * @api-param string $uid 用户id
     * @api-param string $sid 会话id
     * @api-param int $cate 文章分类（可选 1-银行之家 2-物业 默认所有）
     * @api-param string $data 文章信息（json格式：{"title": "文章标题", "logo": "文章logo","content": "文章内容"}）
     * @api-response{
     *      "data":"1",(0-失败 1-成功)
     * }
     */
    public function actionArticlePublish()
    {
        $cate = \Yii::$app->request->post('cate');
        $data = \Yii::$app->request->post('data');
        $data = json_decode($data, true);
        if (empty($data) || empty($cate))
            \Yii::$app->response->error(Error::COMMON_PARAM_INVALID, '参数不合法');
        $result = ArticleService::instance()->articlePublish($cate, $data);
        if (is_null($result))
            \Yii::$app->response->error();
        \Yii::$app->response->success($result);
    }

    /**
     * @api-name 文章详情
     * @api-method GET
     * @api-url forum/article-info
     * @api-param int $articleId 文章id
     * @api-response{
     *   "data": {
     *      "id": 1,文章id
     *      "title": "测试呢文章1",文章标题
     *      "author": "xxx",作者
     *      "createTime": "2017-10-14 12:31:28",发布时间
     *      "content": "",内容
     *      "lookNum": 0,查看数
     *      "commentNum": 0,评论数
     *    }
     * }
     */
    public function actionArticleInfo()
    {
        $articleId = \Yii::$app->request->get('articleId');
        if (empty($articleId))
            \Yii::$app->response->error(Error::COMMON_PARAM_INVALID, '参数不合法');
        $result = ArticleService::instance()->getArticleInfo($articleId);
        if (is_null($result))
            \Yii::$app->response->error();
        \Yii::$app->response->success($result);
    }

    /**
     * @api-name 文章评论列表
     * @api-method GET
     * @api-url forum/comment-list
     * @api-param int $articleId 文章id
     * @api-param int $page 页码
     * @api-param int $pageSize 每页数量
     * @api-response {
     *   "data": {
     *      "page": {
     *        "current": 1,
     *        "total": 1,
     *        "count": 4,
     *        "size": 20
     *          },
     *       "items": [
     *           {
     *        "id": 4,评论id
     *        "pid": 0,评论父节点id
     *        "nickname": "huang",评论人昵称
     *        "headPhoto": null,评论人头像
     *        "content": "这是测试文章评论数据",评论内容
     *       "createTime": "2017-10-15 12:48:08",评论时间
     *          },
     *        ...
     *       ]
     * }
     */
    public function actionCommentList()
    {
        $articleId = \Yii::$app->request->get('articleId');
        if (empty($articleId))
            \Yii::$app->response->error(Error::COMMON_PARAM_INVALID, '参数不合法');
        $page = \Yii::$app->request->get('page');
        $pageSize = \Yii::$app->request->get('pageSize');
        $pager = new Page($page, $pageSize);
        $result = ArticleService::instance()->getArticleCommentList($articleId, $pager);
        if (is_null($result))
            \Yii::$app->response->error();
        \Yii::$app->response->success($result);
    }

    /**
     * @api-name 文章评论
     * @api-method POST
     * @api-url forum/comment
     * @api-param int $articleId 文章id
     * @api-param int $pid 父节点id（选填，目前评论没有迭楼，默认都是0）
     * @api-param int $content 评论内容
     * @api-response {
     *     "data":"true"
     * }
     */
    public function actionComment()
    {
        $articleId = \Yii::$app->request->post('articleId');
        $pid = (int)\Yii::$app->request->post('pid');
        $content = \Yii::$app->request->post('content');

        $articleId = 2;
        $content = "这是测试文章评论数据";

        $result = ArticleService::instance()->articleComment($articleId, $pid, $content);
        if (is_null($result))
            \Yii::$app->response->error();
        \Yii::$app->response->success($result);
    }

}